services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/prometheus:/etc/prometheus.yml
      - prom_data:/prometheus
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - metrics

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: database-test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - metrics
  flyway:
    image: flyway/flyway
    container_name: flyway
    command: [ "-url=jdbc:postgresql://postgres:5432/database-test", "-user=local", "-password=local", "migrate" ]
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - postgres
    networks:
      - metrics

volumes:
  prom_data:
  postgres_data:

networks:
  metrics:
    driver: bridge
