spring:
  application:
    name: exploring-kotlin-coroutines

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: 'false'
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: local
    driver-class-name: org.postgresql.Driver
    username: local
    url: jdbc:postgresql://localhost:5432/task-manager-poc
  flyway:
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web: info
